version: '3.8'

services:
  url-shortener-db:
    image: mysql:8.4
    container_name: url-shortener-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - url-shortener-network
    command:  --mysql-native-password=ON

  redis:
    image: redis:alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    networks:
      - url-shortener-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - url-shortener-db
      - redis
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge

volumes:
  db_data: