FROM golang:1.23-alpine as builder
WORKDIR /app
COPY go.mod go.sum ./

RUN apk update && \
    apk add --no-cache \
    coreutils \
    git \
    make
COPY . .
RUN make build

FROM alpine:3.11
COPY --from=builder /app/bin/linux_amd64/shortener /usr/bin
CMD ["/usr/bin/shortener"]